[package]
name = "matryoshka-cli"
edition.workspace = true
license.workspace = true
version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true

[[bin]]
name = "matryoshka-rs"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
matryoshka-embed-client.workspace = true
matryoshka-enricher.workspace = true
matryoshka-indexer.workspace = true
matryoshka-api.workspace = true
matryoshka-parser.workspace = true
matryoshka-read-api.workspace = true
matryoshka-search.workspace = true
matryoshka-store-sqlite.workspace = true
matryoshka-watcher.workspace = true
serde_json.workspace = true
