[package]
name = "matryoshka-read-api"
edition.workspace = true
license.workspace = true
version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
anyhow.workspace = true
matryoshka-core-ir.workspace = true
matryoshka-store-sqlite.workspace = true
serde.workspace = true
